---
version: '3'
services:
  pdb_postgres_unit:
    image: postgres:14-alpine
    container_name: pdb-postgres-test
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: unit
      POSTGRES_DB: unit
    networks:
      - pdb-unit


networks:
  pdb-unit:
